apiVersion: v1
kind: Service
metadata:
    labels:
        app.kubernetes.io/name: load-balancer-example
    name: network
spec:
    selector:
        app.kubernetes.io/name: load-balancer-example
    type: NodePort
    ports:
        - protocol: TCP
          port: 80
          nodePort: 30080
          targetPort: 3000
