apiVersion: v1
kind: Service
metadata:
    labels:
        app.kubernetes.io/name: load-balancer-example
    name: marcounet-load-balancer
spec:
    selector:
        app.kubernetes.io/name: load-balancer-example
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
